Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [7]:
#Импортируем библиотеку
import numpy as np

In [11]:
N = int(input('Введите число '))
#Создаем массив от 0 до N
n = np.arange(0, N)
#Разворачиваем в обратном порядке
n = n[::-1]
a =  np.array(n)

a

Введите число 10


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [20]:
N = int(input('Введите число '))
#Задаем массив
n = np.arange(0, N)
#разворачиваем в обратном порядке
n = n[::-1]
#задаем матрицу с диагональю n
a = np.diag(n, k=0)

d = np.diagonal(a)
#Находим сумму элементов диагонали
sum_diagonal = np.sum(d)
print(a)

print(sum_diagonal)

Введите число 10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


Задание 3
Решите систему уравнений:
4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [21]:
# коэффициенты при переменных в левой части уравнения

a = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

# значения в правой части уравнения

b = np.array( [4, 12, -3] )

In [22]:
# решение

from numpy import linalg

In [28]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [29]:
# проверка верности

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

Задание 4
В материалах занятия раздел “Задача 4 домашнего задания”
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:
Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [30]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [50]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [73]:

def cosine(users_stats, next_user_stats ):
    #Длина вектора next_user_stats
    next_user_Length = np.linalg.norm( next_user_stats )
    #Задаем счетчики для удобного вывода информации
    user_id = 1
    max_user_id = 0
    max_likeness = 0
#Перебираем элементы матрицы
    for i in users_stats:

               
                    #     # длины векторов
        iLength = np.linalg.norm( i ) 
        #Считаем косинус
        likeness = np.dot( i, next_user_stats ) / ( iLength * next_user_Length )
        print(f'Косинусное сходство ID {user_id}, к next_user = {likeness}')
        if likeness > max_likeness:
            max_likeness = likeness
            max_user_id = user_id
        user_id +=1
       
    print(f'Максимальное сходство ID {max_user_id}, к next_user = {max_likeness}')



In [74]:
cosine(users_stats, next_user_stats )

Косинусное сходство ID 1, к next_user = 0.19999999999999996
Косинусное сходство ID 2, к next_user = 0.8451542547285165
Косинусное сходство ID 3, к next_user = 0.3999999999999999
Косинусное сходство ID 4, к next_user = 0.7905694150420948
Косинусное сходство ID 5, к next_user = 0.3999999999999999
Косинусное сходство ID 6, к next_user = 0.0
Косинусное сходство ID 7, к next_user = 0.0
Косинусное сходство ID 8, к next_user = 0.9486832980505138
Косинусное сходство ID 9, к next_user = 0.0
Косинусное сходство ID 10, к next_user = 0.0
Максимальное сходство ID 8, к next_user = 0.9486832980505138
